CFLAGS = -Wall -g

clean:
	rm -f *.o lobby1 lobby2 lobby3

lobby1:
	$(CC) $(CFLAGS) lobby1.c -o lobby1

lobby2:
	$(CC) $(CFLAGS) lobby2.c -o lobby2

lobby3:
	$(CC) $(CFLAGS) lobby3.c -o lobby3

all: lobby1 lobby2 lobby3

