CFLAGS = -Wall -g

clean:
	rm -f *.o DBLQUOTE JUSTIFY color

DBLQUOTE:
	$(CC) $(CFLAGS) DBLQUOTE.c -o DBLQUOTE

JUSTIFY: 
	$(CC) $(CFLAGS) JUSTIFY.c -o JUSTIFY

color:
	$(CC) $(CFLAGS) color.c -o color

all: DBLQUOTE JUSTIFY color
