CFLAGS = -Wall -g

clean:
	rm -f *.o borc countdown countdown1

borc:
	$(CC) $(CFLAGS) borc.c -o borc

countdown:
	$(CC) $(CFLAGS) countdown.c -o countdown

countdown2:
	$(CC) $(CFLAGS) countdown2.c -o countdown2

all: borc countdown countdown1
