CFLAGS = -Wall -g

clean:
	rm -f *.o GENIE1 GENIE2 GENIE3 taxes

GENIE1:
	$(CC) $(CFLAGS) GENIE1.c -o GENIE1

GENIE2:
	$(CC) $(CFLAGS) GENIE2.c -o GENIE2

GENIE3:
	$(CC) $(CFLAGS) GENIE3.c -o GENIE3

taxes:
	$(CC) $(CFLAGS) taxes.c -o taxes

all: GENIE1 GENIE2 GENIE3 taxes
