CFLAGS = -Wall -g

clean:
	rm -f *.o lights1 lights2 incodd decodd

lights1:
	$(CC) $(CFLAGS) lights1.c -o lights1

lights2:
	$(CC) $(CFLAGS) lights2.c -o lights2

incodd:
	$(CC) $(CFLAGS) incodd.c -o incodd

decodd:
	$(CC) $(CFLAGS) decodd.c -o decodd

all: lights1 lights2 incodd decodd

