CFLAGS = -Wall -g

clean:
	rm -f *.o random random2 random3 random4

random:
	$(CC) $(CFLAGS) random.c -o random

random2:
	$(CC) $(CFLAGS) random2.c -o random2

random3:
	$(CC) $(CFLAGS) random3.c -o random3

random4:
	$(CC) $(CFLAGS) random4.c -o random4

all: random random2 random3 random4
