CFLAGS = -Wall -g

clean:
	rm -f *.o kitty methus methus1

kitty:
	$(CC) $(CFLAGS) kitty.c -o kitty

methus:
	$(CC) $(CFLAGS) methus.c -o methus

methus1:
	$(CC) $(CFLAGS) methus1.c -o methus1

all: kitty methus methus1

